### ISSUE TITLE
Tawk.to use too much cache

### ISSUE THREAD

**Issue by bteamapp** [thirtybees/tawkto#4]

**Comment by getdatakick** [comment]
What do you mean, 'too much cache' ???

**Comment by bteamapp** [comment]
You should adjust your browsing cache leverage so that page speed can be faster. When I remove Tawk.to from the site, the Google Lighthouse score for speed WILL increase and when I install it, it decreases.

**Comment by bteamapp** [comment]
Tawk.io widget takes alot of time to finish loading.

**Comment by getdatakick** [comment]
That's not an issue of thirty bees module, that's problem of tawk.to integration widget itself.
